# Información general
site_name: 'Dibujo y animación'
site_description: 'Apuntes sobre la dibujo y animación digital'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/animate

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/animate'

# Copyright
copyright: '2018 &nbsp; Raul Jesus Lopez'

# Tema
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'pink'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  feature:
#    tabs: true

# Extra
extra:
  search:
    language: 'es, en'
  disqus: 'rauljesus-xyz'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
    - type: 'facebook'
      link: 'https://www.facebook.com/rauljesuslopez'
    - type: 'github'
      link: 'https://github.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'

## CSS Adicional
extra_css:
  - 'stylesheets/extra.css'

# Extensiones
markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'


######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################

# Páginas
nav: 
- Inicio: 'index.md'
- Dibujo: 
    - Inkscape: 'inkscape/index.md'
    - Anexo: 'inkscape/anexo.md'
- Programación: 
    - Scratch: 'scratch/index.md'